modules:
    faq: True
    lists: True
    sfx: True
    games: True
    moderation: True
    economy: True
    obs_ctrl: True

lists:
  movienight: True
  task: True
  bands: True

sfx:
  hooks_timeout: 10 # Timeout period (seconds) between basic hooks cmds
  random_timeout: 0 # Same but for random sfx/folders

games:
  raid: True
  earworm_roulette: True
  cah: True
  
moderation:
  strike_system: True
  reward_system: True

economy:
  streamelements_points: True
  points_gifting: True

obs_ctrl: # You need to install Advanced Scene Switcher OBS Plug-in to use! (refer to docs)
    raid_scene: False # Switch to True if you want a custom raid scene!
    raid_timer: 10 # Delay (seconds) after raid before scene is switched
    victory_scene: False # Separate scene after raids? 
    victory_timer: 0 # Delay (seconds) after victory b4 scene switched to victory_scene
    intro: "scene name"
    main: "scene name"
    talk: "scene name"
    brb: "scene name"
    outro: "scene name"
    raid: "scene name"
    victory: "scene name" # Can be same scene as Talk or completely different
